version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "custom-comprehend-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xi4a1760o1sq"
s3_prefix = "custom-comprehend-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EndpointARN=\"arn:aws:comprehend:us-east-1:313506734225:document-classifier-endpoint/yahoo-answers-endpoint\""
